### PR TITLE
Attempting to add appveyor...

### PR DESCRIPTION
**Pull request by tyler-ball**
@jdmundrawala I don't know how to add `test-kitchen` as an org to appveyor.  On login, I only get an option to login as either my `chef` account or my `tyler-ball` account.  I'm an owner for test-kitchen in Github.

### CODE REVIEW

**Comment by jdmundrawala** [comment]
I think i just added it

**Comment by fnichol** [comment]
Wow, super exciting! Looks like a TravisCI entry failed, I've restarted it…

**Comment by tyler-ball** [comment]
Still getting failures.  Also, specifying ruby as `215` is loading 1.9.3 - ????????

**Comment by fnichol** [comment]
FYI, I've disabled this for the moment to get Cucumber/Aruba back to a green state, then we can circle back and enable this once and for all.

**Comment by cheeseplus** [comment]
Can we get this rebased against master?

**Comment by tyler-ball** [comment]
@cheeseplus Rebased!

**Comment by cheeseplus** [comment]
+1

**Pull request merged**
